version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: AdminPassword123
    volumes:
      - mongodb_data:/data/db
      - ./backup:/backup
    networks:
      - mongo_network

  mongobackup:
    image: tiredofit/db-backup
    container_name: mongobackup
    environment:
      - DB_TYPE=mongo
      - DB_HOST=mongodb
      - DB_NAME=admin
      - DB_USER=admin
      - DB_PASS=AdminPassword123
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - DB_DUMP_TARGET=directory       # Generar carpetas en lugar de archivos
      - DB_DUMP_NAME=backup_%Y%m%d-%H%M%S  # Nombre único con fecha/hora
      - DB_COMPRESSION=false           # Desactivar compresión
    volumes:
      - mongodb_backup:/backup
    depends_on:
      - mongodb
    networks:
      - mongo_network

  webapplication:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapplication
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__ConnectionString=mongodb://admin:AdminPassword123@mongodb:27017/admin
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys
      - mongodb_backup:/app/backups  # Ruta modificada para consistencia
    depends_on:
      - mongodb
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  mongodb_data:
  mongodb_backup:
  dataprotection_keys: