version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: AdminPassword123
    volumes:
      - mongodb_data:/data/db
      - mongodb_backup:/data/backup
    networks:
      - mongo_network  # Conecta solo a la red de MongoDB

  mongobackup:
    image: tiredofit/db-backup
    container_name: mongobackup
    environment:
      - DB_TYPE=mongo
      - DB_HOST=mongodb  # Usa el nombre del servicio, no la IP
      - DB_NAME=admin
      - DB_USER=admin
      - DB_PASS=AdminPassword123
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
    volumes:
      - mongodb_backup:/backup
    depends_on:
      - mongodb
    networks:
      - mongo_network

  webapplication:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapplication
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__ConnectionString=mongodb://admin:AdminPassword123@mongodb:27017/admin
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys
      - mongodb_backup:/backup
    depends_on:
      - mongodb
    networks:
      - mongo_network

networks:
  mongo_network:  # Nueva red con subred diferente
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16  # Subred única para Docker

volumes:
  mongodb_data:
  mongodb_backup:
  dataprotection_keys: